### PR TITLE
docs(ledger-browser): add links to documentation 

### LINKED ISSUE #3550: docs(ledger-browser): add links to documentation
**Is your feature request related to a problem? Please describe.**

Ledger browser apps have an option to provide links to relevant documentation pages. Since documentation for ledger-browser has been commited, we can link it in app definitions.

**Describe the solution you'd like**

Edit eth-browser and fabric-browser app configuration (e.g. https://github.com/hyperledger/cacti/blob/main/packages/cacti-ledger-browser/src/main/typescript/apps/eth/index.tsx) and set their `appDocumentationURL` and `appSetupGuideURL` to point to web docs (e.g. https://hyperledger.github.io/cacti/cactus/ledger-browser/plugin-apps/ethereum-browser/). Setup should point to Setup chapter.

See if links are displayed correctly when using the app (top-right corner) and creating and app (Setup guide link).

**Additional context**

For more info on app config see ledger-browser development guide (https://hyperledger.github.io/cacti/cactus/ledger-browser/developer-guide/overview/)

### PR DESCRIPTION
**Pull request by sirisayshello**
``` 
Changes
----------------
1. Added links to documentation and setup guides for eth-browser and fabric-browser.
```
Fixes #3550 

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Comment by jagpreetsinghsasan** [comment]
@sirisayshello thankyou for your contribution to Hyperledger Cacti.
I have some review comments on this one
1. Can you please comment on the task #3550 with something like `I want to work on this`, so that we can assign you the task. This helps us in avoiding duplications of the efforts spent on its completion.
2. Can you update the `commit message` with what you wrote as the pr description as well? (All you have to do is amend the commit message with the exact copy paste of your pr description, without the `Pull Request Requirements....` paragraph). This helps us with descriptive commit messages and a parity with the PR associated with them.

**Review by jagpreetsinghsasan — DISMISSED** [review]
LGTM with the above requested changes

**Comment by sirisayshello** [comment]
@jagpreetsinghsasan certainly, I will make the requested changes!

**Comment by sirisayshello** [comment]
I have now updated the commit to include the PR description.

**Comment by sirisayshello** [comment]
@outSH Sorry, my bad; I missed that one. I have now made the requested changes!

**Review by outSH — APPROVED** [review]
LGTM, thank you!

**Review by petermetz — APPROVED** [review]

**Comment by jagpreetsinghsasan** [comment]
LGTM (Not approving this intentionally as Peter has already checked and approved, thus dismissing my review)

**Comment by petermetz** [comment]
Closing and re-opening in hopes of triggering the dpull bot

**Pull request merged**
