### PR TITLE
test(connector-besu): migrate get-past-logs-endpoint to Jest

### LINKED ISSUE #3505: test(connector-besu): migrate get-past-logs test cases from Tap to Jest
Migrate all existing test cases for the get past logs endpoint to Jest

### PR DESCRIPTION
**Pull request by Akshitha1020**
## Commit to be reviewed

test(connector-besu): migrate get-past-logs-endpoint to Jest 

     Primary Changes
     ------------------
     1. Updated the migrate get-past-logs-endpoint test 
         to use Jest
     2. Updated the ci.yaml TAPE_TEST_PATTERN to
         incorporate the same

Fixes #3505

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@Akshitha1020 Thank you! LGTM

**Review by petermetz — COMMENTED** [review]
@Akshitha1020 Please fix the lint CI check that failed with the message pasted below:

Error: yarn lint script produced version control side-effects: source files have been changed by it that are otherwise are under version control. This means (99% of the time) that you need to run the yarn lint script locally and then include the changes it makes in your own commit when submitting your pull request.


(you can run the linter locally by doing `yarn lint` on the command line)

**Comment by Akshitha1020** [comment]
Hi @petermetz, tried running `yarn lint` locally, but no issues are found, please find the screenshot attached. Could you please help me resolve this.
image

**Comment by jagpreetsinghsasan** [comment]
@Akshitha1020 after running `yarn lint` you will see some files modified. You have to commit those changes (Please make sure to squash merge all the commits into one single commit before pushing).

In this PR, the lint failed here `packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-past-logs-endpoint.test.ts` line 92 (You need to add a space after `IPluginLedgerConnectorBesuOptions` and before `=`

**Comment by Akshitha1020** [comment]
Hi @jagpreetsinghsasan, I have done the changes as you mentioned, please re-review and let me know.

**Comment by jagpreetsinghsasan** [comment]
@Akshitha1020 all good from my past review comment. There is a merge conflict, can you please resolve that as well?
image

**Comment by petermetz** [comment]
@Akshitha1020 If you are end up struggling with the git operations needed to resolve the merge conflicts just let me know and I can help (You'll just need to invite me as a collaborator to your fork so that I have permission to push to your PR branch directly)

**Comment by Akshitha1020** [comment]
Hi @petermetz, resolved the conflicts but on squashing the commits again it is showing conflicts. I have invited you to be a collaborator to my fork, please accept.

**Comment by petermetz** [comment]
> Hi @petermetz, resolved the conflicts but on squashing the commits again it is showing conflicts. I have invited you to be a collaborator to my fork, please accept.

@Akshitha1020 Okay, no worries! I accepted the invite just now, I'll push the changes soon.

**Review by outSH — APPROVED** [review]

**Pull request merged**
