### PR TITLE
ci(release): add sigstore npm integration through --provenance

### LINKED ISSUE #2623: ci(release): add sigstore npm integration through --provenance
### Description
As a user of the Cacti npm packages I want to see on npmjs.com that the cacti packages are signed so that I have a layer of extra security against supply chain attacks that I can leverage.

https://github.blog/2023-04-19-introducing-npm-package-provenance/
https://blog.sigstore.dev/npm-public-beta/

### Acceptance Criteria
1. The complete list of cacti packages that we are publishing are published with the additional `--provenance` option so that the signature appears publicly on the registries ( for example https://www.npmjs.com/package/@hyperledger/cactus-cmd-api-server )
2. Release process is still fully automated (which is a work in progress task at the time of this writing but nevertheless...)
3. Any changes to the release process should be documented
4. We have to retain the ability to issue releases by multiple maintainers (so signing keys shouldn't be generated/distributed in a way that there's any single point of failure)

### PR DESCRIPTION
**Pull request by adrianbatuto**
## Commit to be reviewed
---
ci(release): add sigstore npm integration through --provenance
```
Primary Changes
----------------
1. Added provenance config to the publish workflows.
```
Fixes #2623

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — COMMENTED** [review]
@adrianbatuto Thank you! Could you please confirm that you've published the packages on the screenshots with the `.github/workflows/all-nodejs-packages-publish.yaml` workflow and not the other one?
If no, then please double check that the mentioned workflow is working as well and then pass it back for review!

**Comment by adrianbatuto** [comment]
Hi peter, I was also able to publish with provenance using all-nodejs-packages-publish.yaml. https://github.com/adrianbatuto/cacti/actions/runs/11801663866

**Comment by adrianbatuto** [comment]
> @adrianbatuto Thank you! Could you please confirm that you've published the packages on the screenshots with the `.github/workflows/all-nodejs-packages-publish.yaml` workflow and not the other one? If no, then please double check that the mentioned workflow is working as well and then pass it back for review!

Hi peter, I was also able to publish with provenance using all-nodejs-packages-publish.yaml. https://github.com/adrianbatuto/cacti/actions/runs/11801663866

**Review by petermetz — APPROVED** [review]
@adrianbatuto Thank you for confirming, in that case we are good to go from my side!

**Comment by jagpreetsinghsasan** [comment]
@hyperledger-cacti/cacti-maintainers requesting review on this PR

**Pull request merged**
