### PR TITLE
feat(cactus-connector-ethereum): add RunTransactionV1Exchange to share receipt data

### PR DESCRIPTION
**Pull request by RafaelAPB**
Also improves watch blocks

Authored-by: Bruno Mateus <brumat315@gmail.com>
Co-authored-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>
Signed-off-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
LGTM

**Comment by RafaelAPB** [comment]
@petermetz are we good to merge this?

**Comment by petermetz** [comment]
@RafaelAPB It looks good to be, but you have to fix the linter failures. A handy trick to get to it faster is to use the browser's text search (CTRL+F) and then type `failing after` and jump through the results to get to the failing job that is marked as required (the lint in  this case)

**Review by outSH — CHANGES_REQUESTED** [review]
Thanks, I've left one comment :)

**Review by outSH — APPROVED** [review]

**Comment by petermetz** [comment]
The `codegen` flaked again, I'm rebasing this to the latest main in preparation for merging. Hopefully this time it doesn't flake.

**Pull request merged**
