### PR TITLE
test: fix all broken validations in packages folder

### LINKED ISSUE #3493: test: fix all broken validations in packages folder
**Describe the bug**

Two tests are failing in the packages folder:

_- From packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts:_ 
1. test("invoke Web3SigningCredentialType.PrivateKeyHex") and 
2. test("invoke Web3SigningCredentialType.CACTUSKEYCHAINREF")

**To Reproduce**

Run these tests in run and debug and note the failing tests in the terminal output. 

**Expected behavior**

The failing tests should pass - contingent upon the jest assertions in those tests also passing. If the test description says the specific function called should return an error, it should return an error and not a resolved promise.

### PR DESCRIPTION
**Pull request by ashnashahgrover**
## **Commit** to be reviewed

test: fix all broken validations in packages folder 
```
 Primary Changes
---------------
1. Fixed broken assertions in deploy-contract-from-json-xdai.test.ts so they assert that 
“Nonce is too low” as expected. 
```
Fixes #3493

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@ashnashahgrover Please fix the commit lint check and make sure to squash the commits into one and rebase onto upstream main

**Comment by RafaelAPB** [comment]
Thank you for the PR. Please fix the lint problems and rebase, as @petermetz mentioned.
Could you please elaborate on the goal of the PR? The description states `1. Fixed broken assertions in deploy-contract-from-json-xdai.test.ts so they assert that “Nonce is too low`, which makes sense, but there are 14 files changed.

**Comment by ashnashahgrover** [comment]
> Thank you for the PR. Please fix the lint problems and rebase, as @petermetz mentioned. Could you please elaborate on the goal of the PR? The description states `1. Fixed broken assertions in deploy-contract-from-json-xdai.test.ts so they assert that “Nonce is too low`, which makes sense, but there are 14 files changed.

I fixed the commit issue. The 14 files changed comes from a mistake I might have made in my understanding.... Since this issue is a dependency of [issue 3483](https://github.com/hyperledger/cacti/issues/3483), I thought I needed to branch it off [issue 3483's](https://github.com/hyperledger/cacti/issues/3483) branch. So it was branched off that and not main. 

Should I just make a new PR with the same changes at this point?

**Comment by petermetz** [comment]
> > Thank you for the PR. Please fix the lint problems and rebase, as @petermetz mentioned. Could you please elaborate on the goal of the PR? The description states `1. Fixed broken assertions in deploy-contract-from-json-xdai.test.ts so they assert that “Nonce is too low`, which makes sense, but there are 14 files changed.
> 
> I fixed the commit issue. The 14 files changed comes from a mistake I might have made in my understanding.... Since this issue is a dependency of [issue 3483](https://github.com/hyperledger/cacti/issues/3483), I thought I needed to branch it off [issue 3483's](https://github.com/hyperledger/cacti/issues/3483) branch. So it was branched off that and not main.
> 
> Should I just make a new PR with the same changes at this point?

@ashnashahgrover No worries! If this is a dependency of another one then we can just mark it as such and then we'll return to the review once the parent PR (the one this depends on) has been merged. Then we can consolidate the diff down to the actual changes that are going into this one and it will all be nice and tidy and easy to review.

No need to start a new PR, more than that, it's explicitly against the contribution guidelines to do so because then the review trail we've established is reset and a lot of duplicate work has to be done to review the new PR again in that case, so no new PRs needed.

Please see my latest post on discord about how to declare the PR dependency: https://discord.com/channels/905194001349627914/908379338716631050/1281022175620366450

> Peter Somogyvari — Today at 3:44 PM
Everyone: We are testing a new PR dependency declaration robot. It works pretty much the same way as the old one did but it looks like it's more permissible with the syntax depends on #??? can be placed anywhere in the PR description within any sentence from what I can tell from their documention (which is this friendly looking gif => https://marketplace-screenshots.githubusercontent.com/7171/4746c300-c629-11ea-85b9-44c0c5ecfe83 )
>
> I've enabled it as a required check on the upstream repo right now so in theory it will just work but please keep me in the loop if you see any problems with any of your pull requests related to the new robot!
>
> Cheers!

**Comment by petermetz** [comment]
@ashnashahgrover Once the parent PR is merged you can just hit the re-request review button and this will pop back up on my radar for a final review (make sure to rebase onto upstream/main right before you request the new review)

**Comment by petermetz** [comment]
Closing this due to inactivity, please feel free to re-open anytime if/when bandwidth is available to take it to the finish line.

**Pull request closed without merging**
