### PR TITLE
feat(bungee-hermes): add BUNGEE package

### PR DESCRIPTION
**Pull request by RafaelAPB**
BUNGEE is an implementation of a view generator https://dl.acm.org/doi/10.1145/3643689

Depends on #3638 and #3639;: #3642, #3643 #3644
Depends on https://github.com/hyperledger-cacti/cacti/pull/3638
Depends on https://github.com/hyperledger-cacti/cacti/pull/3639
Depends on https://github.com/hyperledger-cacti/cacti/pull/3642
Depends on https://github.com/hyperledger-cacti/cacti/pull/3643
Depends on https://github.com/hyperledger-cacti/cacti/pull/3644

Authored-by: Eduardo Vasques <eduardovasques10@tecnico.ulisboa.pt>
Co-authored-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>
Signed-off-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Comment by RafaelAPB** [comment]
@petermetz are we good to merge this?

**Comment by petermetz** [comment]
@RafaelAPB Yes, good from my side. We need another reviewer as well though (another maintainer)

**Review by outSH — APPROVED** [review]
LGTM

Just please divide PR dependencies into separate lines so that our bot can catch them, something like:

- Depends on https://github.com/hyperledger-cacti/cacti/pull/3638
- Depends on https://github.com/hyperledger-cacti/cacti/pull/3639
- Depends on https://github.com/hyperledger-cacti/cacti/pull/3642
- Depends on https://github.com/hyperledger-cacti/cacti/pull/3643
- Depends on https://github.com/hyperledger-cacti/cacti/pull/3644

**Comment by petermetz** [comment]
> LGTM
> 
> Just please divide PR dependencies into separate lines so that our bot can catch them, something like:
> 
>     * Depends on [feat(cactus-core-api): add Ethereum ledger type #3638](https://github.com/hyperledger-cacti/cacti/pull/3638)
> 
>     * Depends on [feat(cactus-consortium): add Ethereum ledger type #3639](https://github.com/hyperledger-cacti/cacti/pull/3639)
> 
>     * Depends on [feat(cactus-connector-besu): add RunTransactionV1Exchange to share receipt data #3642](https://github.com/hyperledger-cacti/cacti/pull/3642)
> 
>     * Depends on [feat(cactus-connector-ethereum): add RunTransactionV1Exchange to share receipt data #3643](https://github.com/hyperledger-cacti/cacti/pull/3643)
> 
>     * Depends on [feat(cactus-connector-fabric): add get transaction receipt by tx id #3644](https://github.com/hyperledger-cacti/cacti/pull/3644)

Good point, thanks for catching that @outSH !

**Comment by RafaelAPB** [comment]
Thanks @outSH and @petermetz

**Comment by petermetz** [comment]
@RafaelAPB There are a few test failures, I'll take a quick look

**Comment by RafaelAPB** [comment]
I pushed a fix by @eduv09 - all should work now

**Comment by petermetz** [comment]
> I pushed a fix by @eduv09 - all should work now

@RafaelAPB Nice, thank you, I'm merging it now!

**Pull request merged**
